import Head from 'next/head'
import Canvas from "../component/Canvas";
import ModelImportTest from "../component/ModelImportTest";
import path from "path";
import fsPromises from 'fs/promises'

export default function(props) {
  const { data } = props;
    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello, Canvas</h1>
        <Canvas />
        <ModelImportTest data={props}/>
      </main>
    </>
  )
}

export const getStaticProps = async () =>{
  const filePath = path.join(process.cwd(), './model/macbook/part1.json');
  const data = await fsPromises.readFile(filePath);
  const objectData = JSON.parse(data);

  return {
    props: objectData,
  };
};